### ISSUE TITLE
1.22 image on Dockerhub is using Go 1.21

### ISSUE THREAD

**Issue by gabek** [bdwyertech/dkr-go-crosscompile#8]
It appears that the 1.22 image that exists on Dockerhub is currently still using Go 1.22. I know 1.22 is added to your workflows for building the image, but it seems like something may have been missing.

Is this line the culprit?
https://github.com/bdwyertech/dkr-go-crosscompile/blob/main/Dockerfile#L1

**Comment by bdwyertech** [comment]
Good catch! Want to make an MR?

**Comment by gabek** [comment]
Will do!

**Comment by bdwyertech** [comment]
I see the real culprit now... Give me a few min.

**Comment by bdwyertech** [comment]
Hey @gabek the root issue is there was no alpine 3.17 image for 1.22.  I can't figure out what libs are missing for alpine 3.18 -- something about iostream not found.  If you wanna take a stab at it, could use a second set of eyes.

**Comment by mahmed2000** [comment]
The build logs say the SDK is missing all the stdlib headers:
> Given SDK does not contain libc++ headers (-stdlib=libc++ test may fail)

Maybe start there?

**Comment by bdwyertech** [comment]
@tpoechtrager any ideas here?  Trying to build [your osxcross](https://github.com/tpoechtrager/osxcross) with alpines clang.  3.17 worked, something changed in alpine 3.18.  Would love any insight you may have...  I may try using your build_clang script rather than using the alpine packages.

```
392.3 testing x86_64h-apple-darwin20.2-clang++ ... /osxcross/oclang/test.cpp:1:10: fatal error: 'iostream' file not found
392.4 testing arm64-apple-darwin20.2-clang++ ... /osxcross/oclang/test.cpp:1:10: fatal error: 'iostream' file not found
392.6 testing arm64e-apple-darwin20.2-clang++ ... /osxcross/oclang/test.cpp:1:10: fatal error: 'iostream' file not found
392.7 testing x86_64-apple-darwin20.2-clang++ ... /osxcross/oclang/test.cpp:1:10: fatal error: 'iostream' file not found
```

**Comment by mahmed2000** [comment]
Its your packaged MacSDK. 8b7954f failed which was also 3.17.

v11.1 (current) `/usr/include/c++/v1` is empty except for a __cxx_version.
v11.3 (before 8b7954f) `/usr/include/c++/v1` actually has libc++ files inside.

Maybe try repackaging them, or v11.1 specifically since that's the one that errored?
https://github.com/tpoechtrager/osxcross/blob/ff8d100f3f026b4ffbe4ce96d8aac4ce06f1278b/tools/gen_sdk_package.sh#L229
This is where the libc++ files gets added, may want to verify Xcode paths since there's no "fail if no libc++" checking there.

**Comment by bdwyertech** [comment]
Hmm...  I'll give that a shot.  Man I hate this cross compilation stuff it's the reason I made this container 😅

**Comment by bdwyertech** [comment]
> Its your packaged MacSDK. [8b7954f](https://github.com/bdwyertech/dkr-go-crosscompile/commit/8b7954f5257efa4bb509b14d7dcbc6ea844ebccd) failed which was also 3.17.
> 
> v11.1 (current) `/usr/include/c++/v1` is empty except for a __cxx_version. v11.3 (before [8b7954f](https://github.com/bdwyertech/dkr-go-crosscompile/commit/8b7954f5257efa4bb509b14d7dcbc6ea844ebccd)) `/usr/include/c++/v1` actually has libc++ files inside.
> 
> Maybe try repackaging them, or v11.1 specifically since that's the one that errored? https://github.com/tpoechtrager/osxcross/blob/ff8d100f3f026b4ffbe4ce96d8aac4ce06f1278b/tools/gen_sdk_package.sh#L229 This is where the libc++ files gets added, may want to verify Xcode paths since there's no "fail if no libc++" checking there.

Good call.  I'll give this a shot.  I will recompile those and try again.  Perhaps its a result of a newer build of Sonoma.  We shall see.

**Comment by bdwyertech** [comment]
Yep, so swapping to the 12.3 SDK seems to have alleviated the issue... I'm going to tweak the package list a bit and push it soon.

**Comment by bdwyertech** [comment]
Should be resolved by https://github.com/bdwyertech/dkr-go-crosscompile/commit/fa67268346bbd25034dd36d0e6c899a22eff57a9

**Comment by gabek** [comment]
Thanks for getting an updated image up! This has been very useful for our project over time, I appreciate you maintaining it.

**Comment by bdwyertech** [comment]
Thanks for spotting the issue.  Takes a village.

**Comment by mahmed2000** [comment]
>  I was hoping to stick to the lowest SDK for purposes of broadest ABI compat but maybe thats not a thing

It probably should be possible. Your v11 and v11.3 sdks have the libc++ headers for example currently. Does repackaging those again also result in no headers?

**Comment by bdwyertech** [comment]
The script that builds those no longer emits an 11.3, and the 11.1 has the things missing.

**Comment by bdwyertech** [comment]
> Its your packaged MacSDK. [8b7954f](https://github.com/bdwyertech/dkr-go-crosscompile/commit/8b7954f5257efa4bb509b14d7dcbc6ea844ebccd) failed which was also 3.17.
> 
> v11.1 (current) `/usr/include/c++/v1` is empty except for a __cxx_version. v11.3 (before [8b7954f](https://github.com/bdwyertech/dkr-go-crosscompile/commit/8b7954f5257efa4bb509b14d7dcbc6ea844ebccd)) `/usr/include/c++/v1` actually has libc++ files inside.
> 
> Maybe try repackaging them, or v11.1 specifically since that's the one that errored? https://github.com/tpoechtrager/osxcross/blob/ff8d100f3f026b4ffbe4ce96d8aac4ce06f1278b/tools/gen_sdk_package.sh#L229 This is where the libc++ files gets added, may want to verify Xcode paths since there's no "fail if no libc++" checking there.

So I figured this out... I do not dev with full XCode, just the Command Line Tools
```
# Xcode Command Line Tools
LIBCXXDIR3="/usr/include/c++/v1"
```

```
k# ls -lah /usr/include/c++/
total 12K    
drwxr-xr-x    3 root     root        4.0K Apr 20 15:59 .
drwxr-xr-x    1 1000     1000        4.0K Nov 22  2021 ..
drwxr-xr-x   13 root     root        4.0K Apr 20 15:59 12.2.1
```
